### PR TITLE
Support incremental protobuf compilation

### PR DESCRIPTION
**Pull request by vjeyakum**

### CODE REVIEW

**Comment by ghost** [comment]
Maybe just make a tetration branch and merge to that?

**Comment by ghost** [comment]
Or maybe we could make an upstream pull request...

**Comment by vjeyakum** [comment]
Since there are no unit tests on this module, I'd like to test it on our repos for a while before sending a PR upstream. :)  Yes, I am merging to release-2.5.0.4 local branch.

**Comment by ghost** [comment]
Hm, I see. So it keeps an `$(outputdirectory)-tmp` around as a sort of cache of what sources are compiled, and if anything is different it copies them into there and compiles them?

LGTM... one could envision just storing hashes instead, but this is dead simple and should do the trick.

**Comment by vjeyakum** [comment]
Yes, that's about right.  It just copies the files from `$(outputdirectory)-tmp` into `$(outputdirectory)` if their contents change, so it should preserve `mtime` of files that haven't changed.

**Pull request merged**
