### PR TITLE
Release 3.1.0.2

### PR DESCRIPTION
**Pull request by pvallem**
Pushing to master, so that we need do these changes for every new tag.

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Comment by vjeyakum** [comment]
Thanks Praneeth.

Since you removed the snapshot suffix, just make sure you upgrade the version number every time you make a fix to this code.

I usually leave snapshot suffix for a while until the code is stable.

**Comment by ghost** [comment]
Yeah, I asked him to remove it so we don't have to constantly redownload
the plugin... We should be OK since its the same code we've been using for
a while.

**Comment by vjeyakum** [comment]
Yep I saw your comment too!  👍🏼

But I have forgotten the snapshot thingy too many times in the past to not
keep reminding people 😄

**Comment by pvallem** [comment]
👍

**Comment by ghost** [comment]
Hate to say it, @vjeyakum but you were right; now we need to emergency patch tetration main_dev because we can't ninja fix the -SNAPSHOT version.

**Comment by vjeyakum** [comment]
Aha. Hope this is the last fix.

**Pull request merged**
